# spring

# server
server:
  title: spring-micro-session
  version: '@project.version@'
  port: 8280

# redis
redis:
  host: localhost
  port: 6379
  database: 0
  password: sOmE_sEcUrE_pAsS
  timeout: 60000

# kafka
kafka:
  bootstrap:
    addresses: localhost:9092
  consumer:
    groupId: session

# documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# logging
logging:
  file:
    name: logs/session.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/session-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 1GB
      max-history: 7
      clean-history-on-start: false
  level:
    io:
      coolexplorer: DEBUG